### ISSUE TITLE
error using dlmwrite

### ISSUE THREAD

**Issue by elijahrockers** [petmri/ROCKETSHIP#13]
Small issue here, it just doesn't seem to want to write the spreadsheets.

```
Error using xlswrite (line 187)
An error occurred on data export in CSV format.

Error in D_fit_voxels_func (line 706)
            xlswrite(xls_path,xls_results);

Error in RUND>done_Callback (line 319)
saved_results = D_fit_voxels_func(results_b_path,dce_model,time_smoothing,time_smoothing_window,xy_smooth_size,number_cpus,roi_list,fit_voxels,neuroecon, outputft);

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in RUND (line 42)
    gui_mainfcn(gui_State, varargin{:});

Error in matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)RUND('done_Callback',hObject,eventdata,guidata(hObject))

Caused by:
    Error using dlmwrite (line 112)
    The input cell array cannot be converted to a matrix.
```

**Comment by ironictoo** [comment]
Have you updated to the latest version of ROCKETSHIP? Also are you sure there is data to output (i.e. make sure there isn't some error further up), I seem to recall if there is no data to write you get this error. What operating system are you using? What Matlab version? 

    On Wednesday, July 13, 2016 8:29 AM, Eli <notifications@github.com> wrote:
 

 Small issue here, it just doesn't seem to want to write the spreadsheets.Error using xlswrite (line 187)
An error occurred on data export in CSV format.Error in D_fit_voxels_func (line 706)
            xlswrite(xls_path,xls_results);

Error in RUND>done_Callback (line 319)
saved_results = D_fit_voxels_func(results_b_path,dce_model,time_smoothing,time_smoothing_window,xy_smooth_size,number_cpus,roi_list,fit_voxels,neuroecon, outputft);

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in RUND (line 42)
    gui_mainfcn(gui_State, varargin{:});

Error in matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)RUND('done_Callback',hObject,eventdata,guidata(hObject))

Caused by:
    Error using dlmwrite (line 112)
    The input cell array cannot be converted to a matrix.

**Comment by ironictoo** [comment]
Update to the latest version, I made some changes in March to handle this kind of thing more gracefully (i.e. not a full crash) and output more detailed error info to help trouble shoot the true issue.

**Comment by elijahrockers** [comment]
Ubuntu 12.04 LTS, MATLAB 2015b. I'm fairly certain we have the latest version, but I'll check on that. I can get access to the results in the MATLAB workspace, and the results are also printed out in the log, so it's not a huge deal.
