### ISSUE TITLE
manual

### ISSUE THREAD

**Issue by doctorbulat** [petmri/ROCKETSHIP#2]
Hello! Great soft! Thanks a lot! everything is perfect! BUT SORRY FOR MY STUPID QUESTION! WHERE IS MANUAL? it is very hard to use it for beginners:( 
Best regards,
Bulat

**Comment by doctorbulat** [comment]
if there is no manual, tell me please what does it mean "data order" in the fitting_gui? what x,y,z, n parameters are? and how to get t1 maps if i have 2 series with flip angles = 2 and 5. what is the order of filling parameters for this 2 series of images?
best regards, 
Bulat.

**Comment by ironictoo** [comment]
Does this mean you found the help files on the GitHub wiki? Did it answer your questions?

Sam

**Comment by doctorbulat** [comment]
Thanks a lot! I just haven't noticed wiki! I will read them properly!

Bulat


>Среда, 27 января 2016, 7:34 -08:00 от Samuel Barnes <notifications@github.com>:
>
>Does this mean you found the help files on the GitHub wiki? Did it answer your questions?
>
>Sam
>
>Sent from my iPhone
>

**Comment by doctorbulat** [comment]
Please help me to get t1 map.
I have 2 series with various flip angles: 2 degrees and 15 degrees.
I have to add two different .nii files for FA=2 degrees and FA=15 degrees (separately). Am i right?
Then in Data order i have to put "x,y,z/file". Am I right? I don't understand what does 'data order' mean from the wiki...
And what parameter values I have to put into TE/TR/FA/TI/B Value list? I put "1.7,5.1,2,15", because I have TE=1.7, TR=5.1, FA1=2, FA2=15 degrees. And why I have to write TR parameter for the second time after TE/TR/FA/TI/B Value list?
Then I put "T1 multi FA Exponential".
But I have a mistake, because the programm writes "wrong number of parameters"...
Sorry for my bad english.
Best regards,
Bulat.


>Среда, 27 января 2016, 7:34 -08:00 от Samuel Barnes <notifications@github.com>:
>
>Does this mean you found the help files on the GitHub wiki? Did it answer your questions?
>
>Sam
>
>Sent from my iPhone
>

**Comment by ironictoo** [comment]
Data order is how the data is arranged, say both of your flip angles were in a single file then the order would be "x,y,z,n". For your case "x,y,z/file" is correct.
For TE/TR/FA/TI/B Value list you could put "2, 15" and that is it. You only put down the variable that is changing. The others (TE, TR, etc.) would be for other mapping techniques.
T1 FA Exponential sounds correct.


 

    On Wednesday, January 27, 2016 12:02 PM, doctorbulat <notifications@github.com> wrote:
 

  Please help me to get t1 map.
I have 2 series with various flip angles: 2 degrees and 15 degrees.
I have to add two different .nii files for FA=2 degrees and FA=15 degrees (separately). Am i right?
Then in Data order i have to put "x,y,z/file". Am I right? I don't understand what does 'data order' mean from the wiki...
And what parameter values I have to put into TE/TR/FA/TI/B Value list? I put "1.7,5.1,2,15", because I have TE=1.7, TR=5.1, FA1=2, FA2=15 degrees. And why I have to write TR parameter for the second time after TE/TR/FA/TI/B Value list?
Then I put "T1 multi FA Exponential".
But I have a mistake, because the programm writes "wrong number of parameters"...
Sorry for my bad english.
Best regards,
Bulat.


>Среда, 27 января 2016, 7:34 -08:00 от Samuel Barnes <notifications@github.com>:
>
>Does this mean you found the help files on the GitHub wiki? Did it answer your questions?
>
>Sam
>
>Sent from my iPhone
>
